"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
Experimental modules
"""
class Sum(nn.Module):
    def __init__(self, n, weight=...) -> None:
        ...
    
    def forward(self, x):
        ...
    


class MixConv2d(nn.Module):
    def __init__(self, c1, c2, k=..., s=..., equal_ch=...) -> None:
        ...
    
    def forward(self, x): # -> Any:
        ...
    


class Ensemble(nn.ModuleList):
    def __init__(self) -> None:
        ...
    
    def forward(self, x, augment=..., profile=..., visualize=...): # -> tuple[Tensor, None]:
        ...
    


def attempt_load(weights, device=..., inplace=..., fuse=...): # -> Module | ModuleList | Ensemble:
    ...

