"""
This type stub file was generated by pyright.
"""

import contextlib
import platform
import threading

"""
utils/initialization
"""
def emojis(str=...): # -> str:
    ...

class TryExcept(contextlib.ContextDecorator):
    def __init__(self, msg=...) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, value, traceback): # -> Literal[True]:
        ...
    


def threaded(func): # -> (*args: Unknown, **kwargs: Unknown) -> Thread:
    ...

def join_threads(verbose=...): # -> None:
    ...

def notebook_init(verbose=...): # -> Module("yolov5.utils.display"):
    ...

