"""
This type stub file was generated by pyright.
"""

"""
Auto-batch utils
"""
def check_train_batch_size(model, imgsz=..., amp=...): # -> int:
    ...

def autobatch(model, imgsz=..., fraction=..., batch_size=...): # -> int:
    ...

