"""
This type stub file was generated by pyright.
"""

from yolov5.utils import TryExcept

"""
AutoAnchor utils
"""
PREFIX = ...
def check_anchor_order(m): # -> None:
    ...

@TryExcept(<Expression>)
def check_anchors(dataset, model, thr=..., imgsz=...): # -> None:
    ...

def kmean_anchors(dataset=..., n=..., img_size=..., thr=..., gen=..., verbose=...): # -> Any | NDArray[float32]:
    """ Creates kmeans-evolved anchors from training dataset

        Arguments:
            dataset: path to data.yaml, or a loaded dataset
            n: number of anchors
            img_size: image size used for training
            thr: anchor-label wh ratio threshold hyperparameter hyp['anchor_t'] used for training, default=4.0
            gen: generations to evolve anchors using genetic algorithm
            verbose: print all results

        Return:
            k: kmeans evolved anchors

        Usage:
            from yolov5.utils.autoanchor import *; _ = kmean_anchors()
    """
    ...

