"""
This type stub file was generated by pyright.
"""

"""
Callback utils
"""
class Callbacks:
    """"
    Handles all registered callbacks for YOLOv5 Hooks
    """
    def __init__(self) -> None:
        ...
    
    def register_action(self, hook, name=..., callback=...): # -> None:
        """
        Register a new action to a callback hook

        Args:
            hook: The callback hook name to register the action to
            name: The name of the action for later reference
            callback: The callback to fire
        """
        ...
    
    def get_registered_actions(self, hook=...): # -> dict[str, list[Unknown]] | list[Unknown]:
        """"
        Returns all the registered actions by callback hook

        Args:
            hook: The name of the hook to check, defaults to all
        """
        ...
    
    def run(self, hook, *args, thread=..., **kwargs): # -> None:
        """
        Loop through the registered actions and fire all callbacks on main thread

        Args:
            hook: The name of the hook to check, defaults to all
            args: Arguments to receive from YOLOv5
            thread: (boolean) Run callbacks in daemon thread
            kwargs: Keyword Arguments to receive from YOLOv5
        """
        ...
    


