"""
This type stub file was generated by pyright.
"""

"""
Download utils
"""
def is_url(url, check=...): # -> bool:
    ...

def gsutil_getsize(url=...): # -> Any | Literal[0]:
    ...

def url_getsize(url=...): # -> int:
    ...

def safe_download(file, url, url2=..., min_bytes=..., error_msg=...): # -> None:
    ...

def attempt_download(file, repo=..., release=..., hf_token=...): # -> str:
    ...

def get_model_filename_from_hfhub(repo_id, hf_token=...): # -> str | None:
    ...

def attempt_donwload_from_hub(repo_id, hf_token=...): # -> str | None:
    ...

