"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
Loss functions
"""
def smooth_BCE(eps=...): # -> tuple[float, float]:
    ...

class BCEBlurWithLogitsLoss(nn.Module):
    def __init__(self, alpha=...) -> None:
        ...
    
    def forward(self, pred, true): # -> Any:
        ...
    


class FocalLoss(nn.Module):
    def __init__(self, loss_fcn, gamma=..., alpha=...) -> None:
        ...
    
    def forward(self, pred, true):
        ...
    


class QFocalLoss(nn.Module):
    def __init__(self, loss_fcn, gamma=..., alpha=...) -> None:
        ...
    
    def forward(self, pred, true):
        ...
    


class ComputeLoss:
    sort_obj_iou = ...
    def __init__(self, model, autobalance=...) -> None:
        ...
    
    def __call__(self, p, targets): # -> tuple[Unknown, Tensor]:
        ...
    
    def build_targets(self, p, targets): # -> tuple[list[Unknown], list[Unknown], list[Unknown], list[Unknown]]:
        ...
    


