"""
This type stub file was generated by pyright.
"""

"""
Image augmentation functions
"""
def mixup(im, labels, segments, im2, labels2, segments2): # -> tuple[Unknown, NDArray[Unknown], NDArray[Unknown]]:
    ...

def random_perspective(im, targets=..., segments=..., degrees=..., translate=..., scale=..., shear=..., perspective=..., border=...): # -> tuple[Any | Unknown, Unknown, ndarray[Any, dtype[Unknown]] | list[Unknown]]:
    ...

