"""
This type stub file was generated by pyright.
"""

class ComputeLoss:
    def __init__(self, model, autobalance=..., overlap=...) -> None:
        ...
    
    def __call__(self, preds, targets, masks): # -> tuple[Unknown, Tensor]:
        ...
    
    def single_mask_loss(self, gt_mask, pred, proto, xyxy, area):
        ...
    
    def build_targets(self, p, targets): # -> tuple[list[Unknown], list[Unknown], list[Unknown], list[Unknown], list[Unknown], list[Unknown]]:
        ...
    


