"""
This type stub file was generated by pyright.
"""

from .. import threaded

@threaded
def plot_images_and_masks(images, targets, masks, paths=..., fname=..., names=...):
    ...

def plot_results_with_masks(file=..., dir=..., best=...): # -> None:
    ...

