"""
This type stub file was generated by pyright.
"""

import sys

"""
Train a YOLOv5 model on a custom dataset.
Models and datasets download automatically from the latest YOLOv5 release.

Usage - Single-GPU training:
    $ yolov5 train --data coco128.yaml --weights yolov5s.pt --img 640  # from pretrained (recommended)
    $ yolov5 train --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640  # from scratch

Usage - Multi-GPU DDP training:
    $ python -m torch.distributed.run --nproc_per_node 4 --master_port 1 train.py --data coco128.yaml --weights yolov5s.pt --img 640 --device 0,1,2,3

Models:     https://github.com/ultralytics/yolov5/tree/master/models
Datasets:   https://github.com/ultralytics/yolov5/tree/master/data
Tutorial:   https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
"""
FILE = ...
ROOT = ...
if str(ROOT) not in sys.path:
    ...
ROOT = ...
LOCAL_RANK = ...
RANK = ...
WORLD_SIZE = ...
def train(hyp, opt, device, callbacks):
    ...

def parse_opt(known=...): # -> Namespace:
    ...

def main(opt, callbacks=...):
    ...

def run(**kwargs): # -> Namespace:
    ...

def run_cli(**kwargs): # -> None:
    '''
    To be called from yolov5.cli
    '''
    ...

if __name__ == "__main__":
    opt = ...
