"""
This type stub file was generated by pyright.
"""

import sys
from yolov5.utils.torch_utils import smart_inference_mode

"""
Validate a trained YOLOv5 detection model on a detection dataset

Usage:
    $ yolov5 val --weights yolov5s.pt --data coco128.yaml --img 640

Usage - formats:
    $ yolov5 val --weights yolov5s.pt                 # PyTorch
                              yolov5s.torchscript        # TorchScript
                              yolov5s.onnx               # ONNX Runtime or OpenCV DNN with --dnn
                              yolov5s_openvino_model     # OpenVINO
                              yolov5s.engine             # TensorRT
                              yolov5s.mlmodel            # CoreML (macOS-only)
                              yolov5s_saved_model        # TensorFlow SavedModel
                              yolov5s.pb                 # TensorFlow GraphDef
                              yolov5s.tflite             # TensorFlow Lite
                              yolov5s_edgetpu.tflite     # TensorFlow Edge TPU
                              yolov5s_paddle_model       # PaddlePaddle
"""
FILE = ...
ROOT = ...
if str(ROOT) not in sys.path:
    ...
ROOT = ...
def save_one_txt(predn, save_conf, shape, file): # -> None:
    ...

def save_one_json(predn, jdict, path, class_map): # -> None:
    ...

def process_batch(detections, labels, iouv): # -> Tensor:
    """
    Return correct prediction matrix
    Arguments:
        detections (array[N, 6]), x1, y1, x2, y2, conf, class
        labels (array[M, 5]), class, x1, y1, x2, y2
    Returns:
        correct (array[N, 10]), for 10 IoU levels
    """
    ...

@smart_inference_mode()
def run(data, weights=..., batch_size=..., batch=..., imgsz=..., img=..., conf_thres=..., iou_thres=..., max_det=..., task=..., device=..., workers=..., single_cls=..., augment=..., verbose=..., save_txt=..., save_hybrid=..., save_conf=..., save_json=..., project=..., name=..., exist_ok=..., half=..., dnn=..., model=..., dataloader=..., save_dir=..., plots=..., callbacks=..., compute_loss=...):
    ...

def parse_opt(): # -> Namespace:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
